import { expect, test } from '@playwright/test'

test.beforeEach(async ({ request }) => { await request.post('/_test/reset') })

test('visual compatível consulta programa legado e evolução sem controles de escrita', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await request.post('/_test/legacy-program')
  await request.post('/_test/evolution')
  const before = await (await request.get('/_test/status')).json()
  await page.goto('/?compat=1')
  const app = page.frameLocator('iframe')
  await expect(app.getByText('Somente leitura', { exact: true })).toBeVisible()
  await app.getByRole('button', { name: 'Abrir carteira' }).click()
  await app.getByRole('textbox', { name: 'Buscar aluno' }).fill('ninguém')
  await expect(app.getByText('Nenhum aluno encontrado para estes filtros.')).toBeVisible()
  await app.getByRole('textbox', { name: 'Buscar aluno' }).fill('MARIANA')
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await expect(app.getByRole('button', { name: 'Pedir revisão do programa' })).toHaveCount(0)
  await app.getByRole('button', { name: 'Treinos', exact: true }).click()
  await expect(app.getByText('Treino anterior', { exact: true })).toBeVisible()
  await expect(app.getByRole('button', { name: 'Preparar alteração' })).toHaveCount(0)
  await app.getByRole('button', { name: 'Evolução', exact: true }).click()
  await expect(app.getByRole('cell', { name: '20', exact: true })).toBeVisible()
  await app.getByLabel('Unidade', { exact: true }).selectOption('lb')
  await expect(app.getByRole('cell', { name: '40', exact: true })).toBeVisible()
  expect(await (await request.get('/_test/status')).json()).toEqual(before)
  expect(await page.evaluate(() => (window as unknown as { messages: unknown[] }).messages)).toEqual([])
  expect(errors).toEqual([])
})
test('card, carteira, aluno e pedido explícito sem mensagens por navegação', async ({ page }) => {
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir carteira' }).click()
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await expect(app.getByRole('heading', { name: 'Mariana', exact: true })).toBeVisible()
  await expect(app.getByText('Dor no ombro relatada pelo aluno')).toBeVisible()
  await app.getByRole('button', { name: 'Treinos', exact: true }).click()
  await expect(app.getByText('Sem programa atual.')).toBeVisible()
  expect(await page.evaluate(() => (window as unknown as { messages: unknown[] }).messages.length)).toBe(0)
  await app.getByRole('button', { name: 'Preparar alteração' }).click()
  await expect.poll(() => page.evaluate(() => (window as unknown as { messages: unknown[] }).messages.length)).toBe(1)
})

test('edição persiste nova revisão, aplicação e restauração usam o backend', async ({ page, request }) => {
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir carteira' }).waitFor()
  await page.getByRole('button', { name: 'Revisar proposta de teste' }).click()
  await app.getByRole('button', { name: 'Revisar proposta', exact: true }).click()
  await app.getByText('Editar proposta', { exact: true }).click()
  await app.getByLabel('Repetições', { exact: false }).fill('12')
  await expect(app.getByRole('button', { name: 'Aplicar programa', exact: true })).toBeDisabled()
  await app.getByRole('button', { name: 'Salvar proposta' }).click()
  await expect(app.getByText(/Revisão da proposta 2/)).toBeVisible()
  await app.getByRole('button', { name: 'Aplicar programa', exact: true }).click()
  await expect(app.getByText(/Programa aplicado em/)).toBeVisible()
  expect((await (await request.get('/_test/status')).json()).revisao).toBe(1)
  await app.getByRole('button', { name: 'Restaurar programa anterior' }).click()
  await expect(app.getByText(/Programa restaurado em/)).toBeVisible()
  expect((await (await request.get('/_test/status')).json()).revisao).toBe(2)
})

test('conexão somente leitura bloqueia escrita de proposta', async ({ page }) => {
  await page.goto('/?read=1')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir carteira' }).waitFor()
  await page.getByRole('button', { name: 'Revisar proposta de teste' }).click()
  await app.getByRole('button', { name: 'Revisar proposta', exact: true }).click()
  await expect(app.getByRole('button', { name: 'Aplicar programa', exact: true })).toBeDisabled()
  await expect(app.getByText('Editar proposta', { exact: true })).toHaveCount(0)
})

test('320 px, tema escuro e foco de teclado sem rolagem horizontal', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 700 })
  await page.goto('/?theme=dark')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir carteira' }).click()
  await expect(app.locator('main')).toHaveAttribute('data-theme', 'dark')
  const frame = page.frames().find(f => f.url().includes('/_test/ui'))!
  expect(await frame.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await app.getByRole('textbox', { name: 'Buscar aluno' }).focus()
  await page.keyboard.press('Tab')
  await expect(app.getByLabel('Mostrar', { exact: true })).toBeFocused()
})

test('resultado externo mantém edições e o aluno original da proposta', async ({ page }) => {
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir carteira' }).waitFor()
  await page.getByRole('button', { name: 'Revisar proposta de teste' }).click()
  await app.getByRole('button', { name: 'Revisar proposta', exact: true }).click()
  await app.getByText('Editar proposta', { exact: true }).click()
  await app.getByLabel('Repetições', { exact: false }).fill('15')
  await page.getByRole('button', { name: 'Revisar proposta de teste' }).click()
  await expect(app.getByText(/Há uma atualização disponível/)).toBeVisible()
  await expect(app.getByLabel('Repetições', { exact: false })).toHaveValue('15')
  await expect(app.getByRole('heading', { name: 'Mariana', exact: true })).toBeVisible()
})

test('evolução consulta o ID exportado e separa unidades do histórico', async ({ page, request }) => {
  const browserErrors: string[] = []
  page.on('pageerror', error => browserErrors.push(error.message))
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir carteira' }).waitFor()
  await page.getByRole('button', { name: 'Revisar proposta de teste' }).click()
  await app.getByRole('button', { name: 'Revisar proposta', exact: true }).click()
  await app.getByRole('button', { name: 'Aplicar programa', exact: true }).click()
  await expect(app.getByText(/Programa aplicado em/)).toBeVisible()
  await request.post('/_test/evolution')
  await app.getByRole('button', { name: 'Ver programa', exact: true }).click()
  await app.getByRole('button', { name: 'Evolução', exact: true }).click()
  await expect(app.getByLabel('Unidade', { exact: true })).toHaveValue('kg')
  await expect(app.getByRole('cell', { name: '20', exact: true })).toBeVisible()
  await expect(app.getByRole('img', { name: /Evolução em kg/ })).toBeVisible()
  await app.getByLabel('Unidade', { exact: true }).selectOption('lb')
  await expect(app.getByRole('cell', { name: '40', exact: true })).toBeVisible()
  await expect(app.getByRole('cell', { name: '20', exact: true })).toHaveCount(0)
  await app.getByLabel('Unidade', { exact: true }).selectOption('unidade não informada')
  await expect(app.getByRole('cell', { name: '10', exact: true })).toBeVisible()
  await expect(app.locator('svg[role="img"]')).toHaveCount(0)
  expect(browserErrors).toEqual([])
})
