import { expect, test, type Page } from '@playwright/test'

test.beforeEach(async ({ request }) => { await request.post('/_test/reset') })

const mensagens = (page: Page) => page.evaluate(() => (window as unknown as { messages: { content: { text: string }[] }[] }).messages.map(m => m.content[0].text))

test('carteira, ficha, treinos e evolução sem escrita e sem mensagem por navegação', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await request.post('/_test/legacy-program')
  await request.post('/_test/evolution')
  const before = await (await request.get('/_test/status')).json()
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await expect(app.getByRole('heading', { name: 'Quem precisa de atenção' })).toBeVisible()
  await app.getByRole('button', { name: 'Abrir carteira' }).click()
  await app.getByRole('textbox', { name: 'Buscar aluno' }).fill('ninguém')
  await expect(app.getByText('Nenhum aluno encontrado para estes filtros.')).toBeVisible()
  await app.getByRole('textbox', { name: 'Buscar aluno' }).fill('MARIANA')
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await expect(app.getByRole('heading', { name: 'Mariana', exact: true })).toBeVisible()
  await expect(app.getByText('Dor no ombro relatada pelo aluno').first()).toBeVisible()
  await app.getByRole('tab', { name: 'Treinos' }).click()
  await expect(app.getByText('Treino anterior', { exact: true })).toBeVisible()
  await app.getByRole('tab', { name: 'Evolução' }).click()
  await expect(app.getByLabel('Unidade', { exact: true })).toHaveValue('kg')
  await expect(app.getByRole('cell', { name: '20', exact: true })).toBeVisible()
  await expect(app.getByText(/^Melhor no período: 20$/)).toBeVisible()
  await app.getByLabel('Unidade', { exact: true }).selectOption('lb')
  await expect(app.getByRole('cell', { name: '40', exact: true })).toBeVisible()
  await expect(app.getByRole('cell', { name: '20', exact: true })).toHaveCount(0)
  // Registro legado sem unidade de carga entra como kg.
  await app.getByLabel('Unidade', { exact: true }).selectOption('kg')
  await expect(app.getByRole('cell', { name: '10', exact: true })).toBeVisible()
  expect(await (await request.get('/_test/status')).json()).toEqual(before)
  expect(await mensagens(page)).toEqual([])
  expect(errors).toEqual([])
})

test('botões da ficha só enviam pedidos à conversa, com aluno e tool publicada', async ({ page, request }) => {
  await request.post('/_test/legacy-program?vencido=1')
  const before = await (await request.get('/_test/status')).json()
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir carteira' }).click()
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await app.getByRole('button', { name: 'Revisar treino' }).click()
  await expect(app.getByText('Pedido enviado na conversa')).toBeVisible()
  await app.getByRole('tab', { name: 'Treinos' }).click()
  await app.getByRole('button', { name: 'Ajustar este treino' }).click()
  await app.getByRole('button', { name: 'Renovar vigência' }).click()
  await app.getByRole('button', { name: 'Trocar Supino' }).click()
  await app.getByRole('button', { name: 'Desfazer última alteração' }).click()
  await expect.poll(async () => (await mensagens(page)).length).toBe(5)
  const [revisar, ajustar, renovar, trocar, desfazer] = await mensagens(page)
  for (const m of [revisar, ajustar, renovar, trocar, desfazer]) expect(m).toMatch(/aluno_id=harness-mariana/)
  expect(revisar).toMatch(/aplicar_programa_treino/)
  expect(ajustar).toMatch(/"Treino anterior".*aplicar_programa_treino/)
  expect(renovar).toMatch(/atualizar_treino/)
  expect(trocar).toMatch(/"Supino".*listar_biblioteca_exercicios/)
  expect(desfazer).toMatch(/desfazer_alteracao_treino/)
  expect(await (await request.get('/_test/status')).json()).toEqual(before)
})

test('pedido não duplica com clique repetido', async ({ page }) => {
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  const revisar = app.getByRole('button', { name: 'Montar primeiro treino' })
  await revisar.click()
  await expect(app.getByText('Pedido enviado na conversa')).toBeVisible()
  await expect(app.locator('button', { hasText: 'Pedido enviado na conversa' })).toBeDisabled()
  await app.locator('button', { hasText: 'Pedido enviado na conversa' }).click({ force: true })
  expect(await mensagens(page)).toHaveLength(1)
})

test('renovar vigência só aparece em treino vencido', async ({ page, request }) => {
  await request.post('/_test/legacy-program')
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir carteira' }).click()
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await app.getByRole('tab', { name: 'Treinos' }).click()
  await expect(app.getByRole('button', { name: 'Ajustar este treino' })).toBeVisible()
  await expect(app.getByRole('button', { name: 'Renovar vigência' })).toHaveCount(0)
})

test('fila da carteira pede atualização com a lista dos alunos filtrados', async ({ page }) => {
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir carteira' }).click()
  await app.getByRole('radio', { name: 'Sem treino vigente' }).click()
  await app.getByRole('button', { name: /Atualizar este aluno com o chat/ }).click()
  await expect.poll(async () => (await mensagens(page))[0] ?? '').toMatch(/sem treino vigente: Mariana \(aluno_id=harness-mariana\).*um por vez/)
})

test('aluno pelo card abre contexto para prescrever, sem tela cheia nem mensagem', async ({ page }) => {
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await expect(app.getByRole('heading', { name: 'Mariana', exact: true })).toBeVisible()
  await expect(app.getByText('Atenção para a prescrição')).toBeVisible()
  await expect(app.getByText('Sem programa vigente')).toBeVisible()
  await expect(app.getByRole('tab')).toHaveCount(0)
  expect(await mensagens(page)).toEqual([])
  await app.getByRole('button', { name: 'Ver ficha' }).click()
  await expect(app.getByRole('tab', { name: 'Visão geral' })).toBeVisible()
})

test('sem tela cheia o card continua limitado e oferece o portal', async ({ page }) => {
  await page.goto('/?nofs=1')
  const app = page.frameLocator('iframe')
  await expect(app.getByRole('button', { name: 'Abrir carteira no portal' })).toBeVisible()
  await expect(app.getByRole('button', { name: 'Abrir carteira', exact: true })).toHaveCount(0)
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await expect(app.getByRole('button', { name: 'Abrir no portal' })).toBeVisible()
  await expect(app.getByRole('button', { name: 'Ver ficha' })).toHaveCount(0)
  await expect(app.getByRole('tab')).toHaveCount(0)
})

test('dados completos carregam em seções e anamnese é legível', async ({ page }) => {
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir carteira' }).click()
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await expect(app.getByText('Postura, Condicionamento')).toBeVisible()
  await expect(app.getByText('Respondeu “não” a 1 pergunta')).toBeVisible()
  await expect(app.getByText(/^(False|True)$/)).toHaveCount(0)
  await app.getByRole('button', { name: 'Carregar', exact: true }).click()
  await expect(app.getByText('Nenhuma avaliação registrada.')).toBeVisible()
  await expect(app.getByText(/contexto aluno|aviso_seguranca/)).toHaveCount(0)
})

test('320 px, tema escuro e foco de teclado sem rolagem horizontal', async ({ page, request }) => {
  await request.post('/_test/legacy-program?vencido=1')
  await page.setViewportSize({ width: 320, height: 700 })
  await page.goto('/?theme=dark')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir carteira' }).click()
  await expect(app.locator('main')).toHaveAttribute('data-theme', 'dark')
  const frame = page.frames().find(f => f.url().includes('/_test/ui'))!
  expect(await frame.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await app.getByRole('textbox', { name: 'Buscar aluno' }).focus()
  await page.keyboard.press('Tab')
  await expect(app.getByRole('radio', { name: 'Todos' })).toBeFocused()
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await app.getByRole('tab', { name: 'Treinos' }).click()
  await expect(app.getByRole('button', { name: 'Renovar vigência' })).toBeVisible()
  expect(await frame.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('treino gravado pela conversa aparece ao atualizar o card, sem recarregar a página', async ({ page, request }) => {
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await expect(app.getByText('Sem programa vigente')).toBeVisible()
  await request.post('/_test/legacy-program')  // gravação feita fora do card
  const before = await (await request.get('/_test/status')).json()
  await app.getByRole('button', { name: 'Atualizar' }).click()
  await expect(app.getByText('Sem programa vigente')).toHaveCount(0)
  await expect(app.getByRole('heading', { name: 'Mariana', exact: true })).toBeVisible()
  expect(await (await request.get('/_test/status')).json()).toEqual(before)
  expect(await mensagens(page)).toEqual([])
})

test('voltar ao card depois de um tempo recarrega sozinho; logo em seguida não', async ({ page, request }) => {
  await page.clock.install()
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await expect(app.getByText('Sem programa vigente')).toBeVisible()
  await request.post('/_test/legacy-program')
  const focar = () => page.frames()[1].evaluate(() => window.dispatchEvent(new Event('focus')))
  await focar()
  await page.waitForTimeout(300)
  await expect(app.getByText('Sem programa vigente')).toBeVisible()
  await page.clock.fastForward(25_000)
  await focar()
  await expect(app.getByText('Sem programa vigente')).toHaveCount(0)
})

test('atenção do card mostra o histórico de dor já respondida por exercício', async ({ page, request }) => {
  await request.post('/_test/dores-respondidas')
  await page.goto('/')
  const app = page.frameLocator('iframe')
  await app.getByRole('button', { name: 'Abrir aluno Mariana' }).click()
  await expect(app.getByText('Atenção para a prescrição')).toBeVisible()
  await expect(app.getByText(/Histórico de dor:\s*Supino 2× · Agachamento 1×/)).toBeVisible()
  await expect(app.getByText('última em 20/09/2026')).toBeVisible()
})
